version: '3'

services:
  SAE_S3_DevWeb:
    image: webdevops/php-apache-dev:8.2-alpine
    container_name: SAE_S3_DevWeb_app
    working_dir: /app/
    ports:
      - 8080:80
    volumes:
      - ./:/app/
  SAE_S3_DevWeb_db:
    image: mysql:8
    container_name: SAE_S3_DevWeb_db
    environment:
      - MYSQL_USER=users
      - MYSQL_DATABASE=Festiplan
      - MYSQL_PASSWORD=sae
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6612:3306"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8 --collation-server=utf8_general_ci 